export const seoConfig: Record<string, { titleKey: string; descKey: string }> = {
  '/': { titleKey: 'seo.home.title', descKey: 'seo.home.description' },
  '/vision-mission': { titleKey: 'seo.vision.title', descKey: 'seo.vision.description' },
  '/ecosystem': { titleKey: 'seo.ecosystem.title', descKey: 'seo.ecosystem.description' },
  '/who-benefits': { titleKey: 'seo.benefits.title', descKey: 'seo.benefits.description' },
  '/beauty-ecosystem': { titleKey: 'seo.beauty.title', descKey: 'seo.beauty.description' },
  '/verticals': { titleKey: 'seo.verticals.title', descKey: 'seo.verticals.description' },
  '/products': { titleKey: 'seo.products.title', descKey: 'seo.products.description' },
  '/market-research': { titleKey: 'seo.research.title', descKey: 'seo.research.description' },
  '/about': { titleKey: 'seo.about.title', descKey: 'seo.about.description' },
  '/insights': { titleKey: 'seo.insights.title', descKey: 'seo.insights.description' },
  '/investors': { titleKey: 'seo.investors.title', descKey: 'seo.investors.description' },
  '/policies': { titleKey: 'seo.policies.title', descKey: 'seo.policies.description' },
  '/legal': { titleKey: 'seo.policies.title', descKey: 'seo.policies.description' },
  '/privacy-policy': { titleKey: 'seo.policies.title', descKey: 'seo.policies.description' },
  '/terms-and-conditions': { titleKey: 'seo.policies.title', descKey: 'seo.policies.description' },
  '/cookie-policy': { titleKey: 'seo.policies.title', descKey: 'seo.policies.description' },
  '/refund-cancellation-policy': { titleKey: 'seo.policies.title', descKey: 'seo.policies.description' },
  '/disclaimer': { titleKey: 'seo.policies.title', descKey: 'seo.policies.description' },
  '/grievance-support': { titleKey: 'seo.policies.title', descKey: 'seo.policies.description' },
};
